import * as vscode from "vscode";
import { marked } from "marked";
import {
  getProvider,
  getAllProviders,
  getOllamaProvider,
  type LLMProvider,
  type ChatMessage,
} from "../providers/index";
import {
  reviewerModelExists,
  createReviewerModel,
  deleteReviewerModel,
  getReviewerModelName,
  unloadOllamaModel,
} from "../ollama/models";
import {
  MAX_EXCHANGES,
  WARN_EXCHANGES,
  SUMMARY_THRESHOLD,
  DEFAULT_MAX_CONTENT_CHARS,
  GUARDRAILS,
  DEFAULT_REVIEW_SYSTEM_PROMPT,
  SUMMARY_SYSTEM_PROMPT,
  SUMMARY_USER_PROMPT,
  type StoredMessage,
  type ChatSession,
  type ReviewResponse,
  type SendChatOpts,
  type SendChatResult,
  DEFAULT_OLLAMA_URL,
} from "../constants";
import { fetchModelsForWebview, sendReviewerModelsForWebview } from "./helpers";
import { buildGitChunks, buildFileChunks, runChunkedReview } from "./reviewBuilder";
import { getHtml } from "./htmlTemplate";

// ---------------------------------------------------------------------------
// SidePanelProvider
// ---------------------------------------------------------------------------

export class SidePanelProvider implements vscode.WebviewViewProvider {
  public static readonly viewType = "raiview.sidePanel";

  // Provider / UI settings
  private activeProvider = "ollama";
  private systemPrompt = "";
  private streamingMode: "chunked" | "complete" = "chunked";
  private enhancedReviewer = false;

  // Chat state
  private chatHistory: StoredMessage[] = [];
  private exchangeCount = 0;
  private currentModel = "";
  private activeSessionTrigger: "git" | "file" | null = null;
  private activeAbortController: AbortController | null = null;
  private reviewCancelled = false;

  // Rolling summary state
  private latestSummary: string | null = null;
  private summaryGenerationId = 0;

  constructor(
    private readonly context: vscode.ExtensionContext,
    private readonly outputChannel: vscode.OutputChannel
  ) {
    const config = vscode.workspace.getConfiguration("raiview");
    this.activeProvider = config.get<string>("defaultProvider") ?? "ollama";
    this.systemPrompt = config.get<string>("defaultSystemPrompt") ?? "";
    this.streamingMode = (config.get<string>("streamingMode") as "chunked" | "complete") ?? "chunked";
    this.enhancedReviewer = config.get<boolean>("enhancedReviewer") ?? false;
    getOllamaProvider().setBaseUrl(config.get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL);

    vscode.workspace.onDidChangeConfiguration(e => {
      if (e.affectsConfiguration("raiview.ollamaUrl")) {
        getOllamaProvider().setBaseUrl(
          vscode.workspace.getConfiguration("raiview").get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL
        );
      }
    }, undefined, context.subscriptions);
  }

  // -------------------------------------------------------------------------
  // API key helpers
  // -------------------------------------------------------------------------

  private async getApiKey(providerName: string): Promise<string | undefined> {
    return this.context.secrets.get(`raiview.apiKey.${providerName}`);
  }

  private async setApiKey(providerName: string, key: string): Promise<void> {
    await this.context.secrets.store(`raiview.apiKey.${providerName}`, key);
  }

  // -------------------------------------------------------------------------
  // Context building
  // -------------------------------------------------------------------------

  private buildSystemPrompt(): string {
    const base = this.systemPrompt.trim() || DEFAULT_REVIEW_SYSTEM_PROMPT;
    const summarySection = this.latestSummary
      ? `\n\nPrior conversation summary:\n${this.latestSummary}`
      : "";
    const priorModels = [...new Set(
      this.chatHistory
        .filter(m => m.role === "assistant" && m.model && m.model !== this.currentModel)
        .map(m => m.model!)
    )];
    const attributionSection = priorModels.length > 0
      ? `\n\nNote: This conversation includes messages previously generated by: ${priorModels.join(", ")}. You are now the active model. Continue the review with full awareness of the prior context — those previous responses were from a different model.`
      : "";
    return `${GUARDRAILS}\n\n${base}${summarySection}${attributionSection}`;
  }

  private buildHistoryForProvider(): ChatMessage[] {
    const all = this.chatHistory.map((m) => ({ role: m.role, content: m.content }));
    if (this.exchangeCount <= SUMMARY_THRESHOLD || !this.latestSummary) { return all; }
    // Summary injected into systemPrompt; only send last 2 exchanges raw
    return all.slice(-4);
  }

  // -------------------------------------------------------------------------
  // Background summary (fire-and-forget, never blocks user)
  // -------------------------------------------------------------------------

  private triggerBackgroundSummary(provider: LLMProvider, apiKey: string | undefined): void {
    if (this.exchangeCount < SUMMARY_THRESHOLD) { return; }
    const genId = ++this.summaryGenerationId;
    const historyText = this.chatHistory
      .map((m) => `${m.role === "user" ? "User" : "Assistant"}: ${m.content}`)
      .join("\n\n");

    provider
      .generate({
        model: this.currentModel,
        prompt: SUMMARY_USER_PROMPT + historyText,
        systemPrompt: SUMMARY_SYSTEM_PROMPT,
        apiKey,
        stream: false,
      })
      .then((summary) => {
        if (genId === this.summaryGenerationId) { this.latestSummary = summary; }
      })
      .catch(() => { /* fail silently */ });
  }

  // -------------------------------------------------------------------------
  // Session persistence
  // -------------------------------------------------------------------------

  private async saveCurrentSession(): Promise<void> {
    if (this.exchangeCount === 0) { return; }
    const sessions = this.context.globalState.get<ChatSession[]>("raiview.chatSessions", []);
    const first = this.chatHistory[0];
    const rawTitle = first?.content ?? "Review session";
    const firstLine = rawTitle.split("\n")[0].trim();
    sessions.unshift({
      id: Date.now().toString(),
      startedAt: first?.timestamp ?? Date.now(),
      title: firstLine.slice(0, 60),
      provider: this.activeProvider,
      model: this.currentModel,
      messages: [...this.chatHistory],
      exchangeCount: this.exchangeCount,
    });
    await this.context.globalState.update("raiview.chatSessions", sessions.slice(0, 5));
  }

  private async startNewSession(webviewView: vscode.WebviewView, fallbackModel?: string): Promise<void> {
    this.reviewCancelled = true;
    if (this.activeAbortController) { this.activeAbortController.abort(); this.activeAbortController = null; }
    await this.saveCurrentSession();
    const config = vscode.workspace.getConfiguration("raiview");
    const modelToUnload = this.currentModel || fallbackModel || "";
    if (this.activeProvider === "ollama" && modelToUnload && config.get<boolean>("autoUnloadModel")) {
      const ollamaUrl = config.get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL;
      try { await unloadOllamaModel(modelToUnload, ollamaUrl, (msg) => this.outputChannel.appendLine(msg)); }
      catch (err: any) { this.outputChannel.appendLine(`[unload] auto-unload failed: ${err.message ?? err}`); }
    }
    this.chatHistory = [];
    this.exchangeCount = 0;
    this.activeSessionTrigger = null;
    this.latestSummary = null;
    this.summaryGenerationId++;
    this.currentModel = "";
    webviewView.webview.postMessage({ type: "newSessionStarted" });
    const sessions = this.context.globalState.get<ChatSession[]>("raiview.chatSessions", []);
    webviewView.webview.postMessage({ type: "historyLoaded", sessions });
  }

  // -------------------------------------------------------------------------
  // Core send method — all AI calls funnel through here
  // -------------------------------------------------------------------------

  private tryParseReview(text: string): ReviewResponse | undefined {
    try { return JSON.parse(text) as ReviewResponse; } catch { /* try recovery */ }
    const lastClose = text.lastIndexOf('"}');
    if (lastClose === -1) { return undefined; }
    const truncated = text.slice(0, lastClose + 2);
    const findingsStart = truncated.indexOf('"findings"');
    if (findingsStart === -1) { return undefined; }
    const arrayStart = truncated.indexOf('[', findingsStart);
    if (arrayStart === -1) { return undefined; }
    try {
      const partial = JSON.parse(truncated.slice(arrayStart) + ']') as import("../constants").ReviewFinding[];
      return { findings: partial, rating: "Needs Minor Changes" };
    } catch { return undefined; }
  }

  async sendChat(opts: SendChatOpts): Promise<SendChatResult> {
    const { prompt, displayText, model, webviewView, isSystemMessage, skipExchangeCount } = opts;
    const attributionModel = opts.displayModel ?? model;
    const provider = getProvider(this.activeProvider);
    if (!provider) {
      webviewView.webview.postMessage({ type: "chatError", message: `Unknown provider: ${this.activeProvider}` });
      return { text: "" };
    }

    const apiKey = await this.getApiKey(this.activeProvider);
    const history = opts.historyOverride !== undefined ? opts.historyOverride : this.buildHistoryForProvider();
    const systemPrompt = this.buildSystemPrompt();
    const isStreaming = this.streamingMode === "chunked";

    if (this.exchangeCount === 0 && !skipExchangeCount) {
      this.outputChannel.show(true);
    }
    const userTimestamp = Date.now();
    const config = vscode.workspace.getConfiguration("raiview");
    const numCtx = this.activeProvider === "ollama" ? (config.get<number>("ollamaContextWindow") ?? 8192) : undefined;
    const numPredict = this.activeProvider === "ollama" ? (config.get<number>("ollamaNumPredict") ?? 2000) : undefined;

    this.currentModel = model;

    webviewView.webview.postMessage({
      type: isSystemMessage ? "systemMessage" : "userMessage",
      text: displayText,
      timestamp: userTimestamp,
    });

    this.chatHistory.push({ role: "user", content: prompt, timestamp: userTimestamp });

    const abortController = new AbortController();
    this.activeAbortController = abortController;

    webviewView.webview.postMessage({ type: "generationStarted" });

    try {
      webviewView.webview.postMessage({ type: "aiThinking" });

      let fullResponse = "";

      if (isStreaming) {
        webviewView.webview.postMessage({ type: "streamStart" });
        let accumulated = "";
        let parseTimer: ReturnType<typeof setTimeout> | null = null;

        const sendParsedUpdate = async () => {
          try {
            const html = await marked(accumulated);
            webviewView.webview.postMessage({ type: "streamUpdate", html });
          } catch { /* ignore during streaming */ }
        };

        fullResponse = await provider.generate({
          model,
          prompt,
          systemPrompt,
          apiKey,
          stream: true,
          history,
          signal: abortController.signal,
          numCtx,
          numPredict,
          jsonSchema: opts.jsonSchema,
          onToken: (token: string) => {
            accumulated += token;
            if (!parseTimer) {
              parseTimer = setTimeout(() => { parseTimer = null; sendParsedUpdate(); }, 300);
            }
          },
          onUsage: (inputTokens: number, outputTokens: number) => {
            this.outputChannel.appendLine(
              `[${new Date().toLocaleTimeString()}] ${this.activeProvider} / ${model}` +
              ` | input: ${inputTokens.toLocaleString()} tokens` +
              ` | output: ${outputTokens.toLocaleString()} tokens` +
              ` | total: ${(inputTokens + outputTokens).toLocaleString()} tokens`
            );
          },
        });

        if (parseTimer) { clearTimeout(parseTimer); }
        const structured = opts.jsonSchema ? this.tryParseReview(fullResponse) : undefined;
        const html = structured ? undefined : await marked(fullResponse);
        webviewView.webview.postMessage({ type: "streamEnd", html, structured, model: attributionModel, timestamp: Date.now() });
      } else {
        fullResponse = await provider.generate({
          model,
          prompt,
          systemPrompt,
          apiKey,
          stream: false,
          history,
          signal: abortController.signal,
          numCtx,
          numPredict,
          jsonSchema: opts.jsonSchema,
          onUsage: (inputTokens: number, outputTokens: number) => {
            this.outputChannel.appendLine(
              `[${new Date().toLocaleTimeString()}] ${this.activeProvider} / ${model}` +
              ` | input: ${inputTokens.toLocaleString()} tokens` +
              ` | output: ${outputTokens.toLocaleString()} tokens` +
              ` | total: ${(inputTokens + outputTokens).toLocaleString()} tokens`
            );
          },
        });
        const structured = opts.jsonSchema ? this.tryParseReview(fullResponse) : undefined;
        const html = structured ? undefined : await marked(fullResponse);
        webviewView.webview.postMessage({ type: "chatMessage", html, structured, model: attributionModel, timestamp: Date.now() });
      }

      this.chatHistory.push({ role: "assistant", content: fullResponse, timestamp: Date.now(), model, provider: this.activeProvider });
      if (!skipExchangeCount) { this.exchangeCount++; }

      webviewView.webview.postMessage({ type: "showFollowup" });
      webviewView.webview.postMessage({ type: "exchangeUpdate", count: this.exchangeCount, limit: MAX_EXCHANGES, warn: WARN_EXCHANGES });

      this.triggerBackgroundSummary(provider, apiKey);

      let structured: ReviewResponse | undefined;
      if (opts.jsonSchema) {
        try { structured = JSON.parse(fullResponse) as ReviewResponse; } catch { /* fallback */ }
      }
      return { text: fullResponse, structured };

    } catch (err: any) {
      if (err?.name === "AbortError" || abortController.signal.aborted) {
        webviewView.webview.postMessage({ type: "generationStopped" });
      } else {
        this.chatHistory.pop();
        webviewView.webview.postMessage({ type: "chatError", message: `${provider.displayName} error: ${err.message ?? err}` });
      }
      return { text: "" };
    } finally {
      if (this.activeAbortController === abortController) { this.activeAbortController = null; }
      webviewView.webview.postMessage({ type: "generationEnded" });
    }
  }

  // -------------------------------------------------------------------------
  // Webview view resolver
  // -------------------------------------------------------------------------

  resolveWebviewView(webviewView: vscode.WebviewView) {
    const mediaUri = vscode.Uri.joinPath(this.context.extensionUri, 'media');
    webviewView.webview.options = { enableScripts: true, localResourceRoots: [mediaUri] };
    const scriptUri = webviewView.webview.asWebviewUri(
      vscode.Uri.joinPath(this.context.extensionUri, 'media', 'webview.js')
    );
    const version: string = this.context.extension.packageJSON.version ?? '';
    webviewView.webview.html = getHtml(scriptUri, version);

    webviewView.webview.onDidReceiveMessage(async (message) => {
      switch (message.command) {
        case "ready": await this.handleReady(webviewView); break;
        case "refreshModels": await fetchModelsForWebview(this.activeProvider, await this.getApiKey(this.activeProvider), webviewView); break;
        case "saveOllamaUrl": await this.handleSaveOllamaUrl(message, webviewView); break;
        case "savePinnedModels": await this.handleSavePinnedModels(message, webviewView); break;
        case "setProvider": await this.handleSetProvider(message, webviewView); break;
        case "setApiKey": await this.handleSetApiKey(message, webviewView); break;
        case "clearApiKey": await this.handleClearApiKey(message, webviewView); break;
        case "reviewChanges": await this.handleReviewChanges(message, webviewView); break;
        case "sendToProvider": await this.handleSendToProvider(message, webviewView); break;
        case "stopGeneration": this.reviewCancelled = true; this.activeAbortController?.abort(); this.activeAbortController = null; break;
        case "followUp": await this.handleFollowUp(message, webviewView); break;
        case "newSession": await this.startNewSession(webviewView, message.model); break;
        case "loadSession": await this.handleLoadSession(message, webviewView); break;
        case "clearHistory": await this.context.globalState.update("raiview.chatSessions", []); webviewView.webview.postMessage({ type: "historyLoaded", sessions: [] }); break;
        case "freeMemory": await this.handleFreeMemory(message, webviewView); break;
        case "setSystemPrompt": this.systemPrompt = message.prompt; break;
        case "toggleStreaming": this.streamingMode = message.mode; break;
        case "toggleEnhancedReviewer": this.enhancedReviewer = message.enabled; break;
        case "createReviewerModel": await this.handleCreateReviewerModel(message, webviewView); break;
        case "deleteReviewerModelByName": await this.handleDeleteReviewerModel(message, webviewView); break;
      }
    });
  }

  // -------------------------------------------------------------------------
  // Message handlers
  // -------------------------------------------------------------------------

  private async handleReady(webviewView: vscode.WebviewView): Promise<void> {
    const hasKey = !!(await this.getApiKey(this.activeProvider));
    const providerKeyStatus: Record<string, boolean> = {};
    for (const p of getAllProviders()) {
      providerKeyStatus[p.name] = !!(await this.getApiKey(p.name));
    }
    webviewView.webview.postMessage({
      type: "init",
      providers: getAllProviders().map((p) => ({ name: p.name, displayName: p.displayName, requiresApiKey: p.requiresApiKey })),
      activeProvider: this.activeProvider,
      hasApiKey: hasKey,
      providerKeyStatus,
      streamingMode: this.streamingMode,
      enhancedReviewer: this.enhancedReviewer,
      systemPrompt: this.systemPrompt,
      autoUnloadModel: vscode.workspace.getConfiguration("raiview").get<boolean>("autoUnloadModel") ?? false,
      ollamaUrl: vscode.workspace.getConfiguration("raiview").get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL,
      ollamaModels: vscode.workspace.getConfiguration("raiview").get<string[]>("ollamaModels") ?? [],
    });
    fetchModelsForWebview(this.activeProvider, await this.getApiKey(this.activeProvider), webviewView);
    const sessions = this.context.globalState.get<ChatSession[]>("raiview.chatSessions", []);
    webviewView.webview.postMessage({ type: "historyLoaded", sessions });
  }

  private async handleSaveOllamaUrl(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const newUrl = ((message.url as string) ?? "").trim() || DEFAULT_OLLAMA_URL;
    await vscode.workspace.getConfiguration("raiview").update("ollamaUrl", newUrl, vscode.ConfigurationTarget.Global);
    getOllamaProvider().setBaseUrl(newUrl);
    if (this.activeSessionTrigger !== null) {
      webviewView.webview.postMessage({ type: "systemMessage", text: `Ollama URL changed to ${newUrl} mid-session. The full conversation history will be sent to this endpoint.` });
    }
    fetchModelsForWebview("ollama", await this.getApiKey("ollama"), webviewView);
  }

  private async handleSavePinnedModels(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const models = (message.models as string[]).filter(Boolean);
    await vscode.workspace.getConfiguration("raiview").update("ollamaModels", models, vscode.ConfigurationTarget.Global);
    fetchModelsForWebview("ollama", await this.getApiKey("ollama"), webviewView);
  }

  private async handleSetProvider(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const newProvider = message.provider;
    if (this.activeSessionTrigger !== null && newProvider !== this.activeProvider && (getProvider(newProvider)?.requiresApiKey ?? false)) {
      const displayName = getProvider(newProvider)?.displayName ?? newProvider;
      webviewView.webview.postMessage({ type: "systemMessage", text: `Switched to ${displayName} mid-session. The full conversation history will be shared with this model and may consume tokens.` });
    }
    this.activeProvider = newProvider;
    const apiKey = await this.getApiKey(this.activeProvider);
    webviewView.webview.postMessage({
      type: "providerChanged",
      provider: this.activeProvider,
      hasApiKey: !!apiKey,
      requiresApiKey: getProvider(this.activeProvider)?.requiresApiKey ?? false,
    });
    fetchModelsForWebview(this.activeProvider, apiKey, webviewView);
  }

  private async handleSetApiKey(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const target = message.provider ?? this.activeProvider;
    const inlineKey = (message.key as string | undefined)?.trim() ?? "";
    let keyValue: string;
    if (inlineKey.length > 5) {
      keyValue = inlineKey;
    } else {
      const input = await vscode.window.showInputBox({
        prompt: `Enter your ${getProvider(target)?.displayName ?? target} API key`,
        password: true,
        ignoreFocusOut: true,
      });
      if (!input || input.trim().length <= 5) { return; }
      keyValue = input.trim();
    }
    await this.setApiKey(target, keyValue);
    const isActive = target === this.activeProvider;
    webviewView.webview.postMessage({ type: "apiKeySet", provider: target, hasApiKey: true, isActiveProvider: isActive });
    if (isActive) { fetchModelsForWebview(this.activeProvider, keyValue, webviewView); }
    vscode.window.showInformationMessage(`${getProvider(target)?.displayName} API key saved securely.`);
  }

  private async handleClearApiKey(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const target = message.provider ?? this.activeProvider;
    await this.context.secrets.delete(`raiview.apiKey.${target}`);
    const isActive = target === this.activeProvider;
    webviewView.webview.postMessage({ type: "apiKeyCleared", provider: target, isActiveProvider: isActive });
    if (isActive) { fetchModelsForWebview(this.activeProvider, undefined, webviewView); }
  }

  private async handleReviewChanges(message: any, webviewView: vscode.WebviewView): Promise<void> {
    if (this.activeAbortController) { return; }
    const userSelectedGitModel = message.model;
    let model = message.model;
    if (this.enhancedReviewer && this.activeProvider === "ollama") {
      const reviewerName = getReviewerModelName(model);
      if (model !== reviewerName) {
        const ollamaUrl = vscode.workspace.getConfiguration("raiview").get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL;
        if (await reviewerModelExists(ollamaUrl, model)) { model = reviewerName; }
      }
    }
    const gitChunks = await buildGitChunks(webviewView, this.maxContentChars, this.outputChannel);
    if (!gitChunks) { return; }
    if (this.activeSessionTrigger === null) {
      this.activeSessionTrigger = "git";
      webviewView.webview.postMessage({ type: "sessionTriggered", trigger: "git" });
    }
    await runChunkedReview(
      gitChunks, model, webviewView,
      this.exchangeCount === 0 ? "Reviewing git changes..." : "Re-reviewing git changes...",
      (opts) => this.sendChat(opts),
      () => this.reviewCancelled,
      (v) => { this.reviewCancelled = v; },
      this.maxContentChars,
      userSelectedGitModel
    );
  }

  private async handleSendToProvider(message: any, webviewView: vscode.WebviewView): Promise<void> {
    if (this.activeAbortController) { return; }
    const userSelectedFileModel = message.model;
    let model = message.model;
    if (this.enhancedReviewer && this.activeProvider === "ollama") {
      const reviewerName = getReviewerModelName(model);
      if (model !== reviewerName) {
        const ollamaUrl = vscode.workspace.getConfiguration("raiview").get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL;
        if (await reviewerModelExists(ollamaUrl, model)) { model = reviewerName; }
      }
    }
    const fileChunks = await buildFileChunks(message.customInput ?? "", webviewView, this.maxContentChars);
    if (!fileChunks) { return; }
    if (this.activeSessionTrigger === null) {
      this.activeSessionTrigger = "file";
      webviewView.webview.postMessage({ type: "sessionTriggered", trigger: "file" });
    }
    await runChunkedReview(
      fileChunks, model, webviewView,
      this.exchangeCount === 0 ? "Reviewing active file..." : "Re-reviewing active file...",
      (opts) => this.sendChat(opts),
      () => this.reviewCancelled,
      (v) => { this.reviewCancelled = v; },
      this.maxContentChars,
      userSelectedFileModel
    );
  }

  private async handleFollowUp(message: any, webviewView: vscode.WebviewView): Promise<void> {
    if (this.exchangeCount >= MAX_EXCHANGES) { return; }
    const model = message.model || this.currentModel;
    await this.sendChat({ prompt: message.content, displayText: message.content, model, webviewView });
  }

  private async handleLoadSession(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const sessions = this.context.globalState.get<ChatSession[]>("raiview.chatSessions", []);
    const session = sessions.find((s) => s.id === message.sessionId);
    if (!session) { return; }
    const renderedMessages = await Promise.all(
      session.messages.map(async (m) => {
        if (m.role === "assistant") {
          const structured = this.tryParseReview(m.content);
          if (structured) { return { ...m, structured }; }
          return { ...m, html: await marked(m.content) };
        }
        return { ...m };
      })
    );
    webviewView.webview.postMessage({ type: "sessionView", session: { ...session, messages: renderedMessages } });
  }

  private async handleFreeMemory(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const modelToUnload = this.currentModel || message.model || "";
    this.outputChannel.appendLine(`[freeMemory] received — provider: ${this.activeProvider}, currentModel: "${this.currentModel}", messageModel: "${message.model}", using: "${modelToUnload}"`);
    if (this.activeProvider === "ollama" && modelToUnload) {
      const ollamaUrl = vscode.workspace.getConfiguration("raiview").get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL;
      this.outputChannel.appendLine(`[freeMemory] sending keep_alive:0 to ${ollamaUrl} for model "${modelToUnload}"`);
      webviewView.webview.postMessage({ type: "freeMemoryStatus", loading: true });
      try {
        await unloadOllamaModel(modelToUnload, ollamaUrl, (msg) => this.outputChannel.appendLine(msg));
        this.outputChannel.appendLine(`[freeMemory] unload completed successfully`);
        webviewView.webview.postMessage({ type: "freeMemoryStatus", loading: false });
        webviewView.webview.postMessage({ type: "systemMessage", text: `Model ${modelToUnload} unloaded from GPU memory.` });
      } catch (err: any) {
        this.outputChannel.appendLine(`[freeMemory] unload failed: ${err.message ?? err}`);
        webviewView.webview.postMessage({ type: "freeMemoryStatus", loading: false });
        webviewView.webview.postMessage({ type: "chatError", message: `Failed to unload model: ${err.message ?? err}` });
      }
    } else {
      this.outputChannel.appendLine(`[freeMemory] skipped — condition not met (provider must be ollama with a loaded model)`);
    }
  }

  private async handleCreateReviewerModel(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const ollamaUrl = vscode.workspace.getConfiguration("raiview").get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL;
    try {
      webviewView.webview.postMessage({ type: "reviewerModelStatus", status: "creating" });
      const config = vscode.workspace.getConfiguration("raiview");
      const numCtx = config.get<number>("ollamaContextWindow") ?? 4096;
      const numPredict = config.get<number>("ollamaNumPredict") ?? 2000;
      await createReviewerModel(message.baseModel, ollamaUrl, (progressStatus: string) => {
        webviewView.webview.postMessage({ type: "reviewerModelStatus", status: "progress", message: progressStatus });
      }, numCtx, numPredict);
      webviewView.webview.postMessage({ type: "reviewerModelStatus", status: "created" });
      vscode.window.showInformationMessage(`code-reviewer model created from ${message.baseModel}.`);
      await fetchModelsForWebview(this.activeProvider, await this.getApiKey(this.activeProvider), webviewView);
    } catch (err: any) {
      webviewView.webview.postMessage({ type: "reviewerModelStatus", status: "error", message: err.message ?? String(err) });
    }
  }

  private async handleDeleteReviewerModel(message: any, webviewView: vscode.WebviewView): Promise<void> {
    const ollamaUrl = vscode.workspace.getConfiguration("raiview").get<string>("ollamaUrl") ?? DEFAULT_OLLAMA_URL;
    try {
      await deleteReviewerModel(ollamaUrl, undefined, message.modelName);
      vscode.window.showInformationMessage(`${message.modelName} deleted.`);
      await fetchModelsForWebview(this.activeProvider, await this.getApiKey(this.activeProvider), webviewView);
    } catch (err: any) {
      webviewView.webview.postMessage({ type: "reviewerModelStatus", status: "error", message: err.message ?? String(err) });
    }
  }

  // -------------------------------------------------------------------------
  // Config helpers
  // -------------------------------------------------------------------------

  private get maxContentChars(): number {
    return vscode.workspace.getConfiguration("raiview").get<number>("maxContentChars") ?? DEFAULT_MAX_CONTENT_CHARS;
  }
}
